@startuml
left to right direction
'skinparam linetype ortho

title Diagrama de Contexto: MiComedorUCV

rectangle "MiComedorUCV" as Comedor

actor "Estudiante" as Estudiante
actor "Personal de Atención" as P_At

cloud "Sistema Académico UCV" as SA

Estudiante -- (Comedor) : Consulta Menú >
Estudiante -- (Comedor) : < Recibe QR Para \nVerificación

P_At -- (Comedor) : Verifica Acceso >
P_At -- (Comedor) : Reporta Incidencias\n(Técnicas) >

SA -- (Comedor) : < Validar Estatus\nEstudiante 
(Comedor) -- SA : < Confirma Matrícula /\nDatos Básicos

@enduml