@startuml use-cases
left to right direction

:Usuario:
:BaseDeDatosUCV:
:Administrador:

rectangle "MiComedorUCV" {
	usecase IniciarSesión
	usecase GestionarMenú
	usecase VerMenú
	usecase VerTurnos
	usecase RealizarReporte
	usecase VerificarSuministros
	usecase Registrarse
	usecase GestionarTurnos
}


Usuario -- VerTurnos
VerMenú <. VerTurnos : <<include>>

Registrarse .> IniciarSesión : <<extend>>
Usuario -- Registrarse

Usuario -- IniciarSesión
BaseDeDatosUCV -- IniciarSesión
Administrador -- IniciarSesión

Administrador -- RealizarReporte
Administrador -- VerificarSuministros
Administrador -- GestionarMenú
Administrador -- GestionarTurnos

@enduml
