@startuml Requeriments
left to right direction

:Cliente:
:Administrador:
:BaseDeDatos:

rectangle "MiComedorUCV" {
	usecase IniciarSesión
	usecase GestionarMenú
	usecase VerMenú
	usecase VerTurnos
	usecase RealizarReporte
	usecase VerificarSuministros
	usecase AccederComoUsuario
	usecase AccederComoAdministrador
}

Administrador -- IniciarSesión
Cliente -- IniciarSesión
BaseDeDatos -- IniciarSesión

IniciarSesión <.. AccederComoAdministrador : <<include>>
IniciarSesión <.. AccederComoUsuario : <<include>>
AccederComoUsuario <. VerMenú : <<extend>>
VerMenú .> VerTurnos : <<include>>

AccederComoAdministrador <.. RealizarReporte : <<extend>>
AccederComoAdministrador <.. VerificarSuministros : <<extend>>
AccederComoAdministrador <. GestionarMenú : <<extend>>


@enduml