@startuml v

Class Administrador
Class Cocina
Class Pedido
Class Reporte
Class Cliente {
	string tipoDeCliente
}
Class Turno {
	int horario
	int capacidadMaxima
}
Class Insumo {
	float cantidad 
}
Class Menu {
	bool disponibilidad
}

Insumo "0..*" -o Menu
Insumo -- Administrador : < Maneja
Insumo "1..*" --> Reporte 

Menu --  Cliente : < Selecciona

Administrador -- Turno : Asigna >
Administrador - Menu : Gestiona >
Administrador -- Reporte : Genera >

Cliente "1..*" --> Turno
Cliente --o Pedido

Turno "0..1" o-- "1..*" Menu

Pedido *-- Menu
Pedido "1..*" --> Reporte

Cocina -- Pedido : Prepara >
Turno --> Reporte

@enduml