@startuml domain-modeling

state eleccionElegirActividad <<choice>>
state eleccionTrabajar <<choice>>

[*] --> eleccionElegirActividad : iniciandoJornada

eleccionElegirActividad --> reporteRedactado : redactandoReporte
reporteRedactado --> reportePresentado : presentandoReporte
reportePresentado --> eleccionTrabajar : continuarTrabajando?

eleccionElegirActividad --> menuModificado : modificandoMenu
menuModificado --> menuPresentado : presentandoMenu
menuPresentado --> eleccionTrabajar : continuarTrabajando?

eleccionElegirActividad --> suministrosVerificados : verificandoSuministros
suministrosVerificados --> cantidadesAnotadas : anotandoCantidades
cantidadesAnotadas --> eleccionTrabajar : continuarTrabajando?

eleccionTrabajar --> eleccionElegirActividad : si
eleccionTrabajar --> [*] : terminandoJornada

@enduml
