@startuml domain-modeling

state a <<choice>>

[*] --> ingresadoAlComedor

ingresadoAlComedor -> a : finDeLaCola?

a --> ingresadoAlComedor: no
a --> tomadaBandeja : si

tomadaBandeja --> asientoEncontrado : buscandoAsiento
asientoEncontrado --> comidaTerminada : comiendo
comidaTerminada --> bandejaDevuelta : devolviendoComida
bandejaDevuelta --> [*] : saliendoDelComedor

@enduml