@startuml

state a <<choice>>
state b <<choice>>
state c <<choice>>
[*]-->Preparado : Preparando
Preparado-->a : Trabajar?
a-->b : Yes
a-->Irse : No
Irse-->[*]
b-->Reporte_redactado : Redactando reporte
Reporte_redactado-->Reporte_presentado : Presentando reporte
Reporte_presentado-->c : Continuar trabajando?
b-->Menu_modificado : Modificando menu
Menu_modificado-->Menu_presentado : Presentado menu
Menu_presentado-->c : Continuar trabajando?
b-->Suministros_Verificados : Verificando suministros
Suministros_Verificados-->Cantidades_anotadas : Anotando cantidades
Cantidades_anotadas-->c : Continuar trabajando?
c-->b : Yes
c-->Irse : No
@enduml
