@startuml
!define RECTANGLE_COLOR #DDDDDD
!define ACTOR_COLOR #AAAAAA

skinparam Linetype ortho

'Mayor separación horizontal
skinparam nodesep 150

'Mayor separación vertical
skinparam ranksep 200    

'Más espacio dentro de los elementos
skinparam padding 20       

title Diagrama de Contexto: MiComedorUCV

rectangle "    MiComedorUCV    " as Comedor <<Sistema>> RECTANGLE_COLOR

actor "Estudiante" as Estudiante ACTOR_COLOR
'actor "Personal del Comedor" as Personal ACTOR_COLOR
'actor "Proveedor" as Proveedor ACTOR_COLOR
actor "Administración" as Admin ACTOR_COLOR
'actor "Sistema Gestión Académica" as SGA ACTOR_COLOR

Estudiante -- (Comedor) : Solicita/Paga Comida ->
(Comedor) -left- Estudiante : <- Sirve \lComida/Recibo

'Personal -- (Comedor) : Solicitudes \lMantenimiento ->
'(Comedor) -- Personal : <- Información \lMenú/Órdenes Compra

'Proveedor -- (Comedor) : Entrega \lProductos/Facturas ->
'(Comedor) -- Proveedor : <- Órdenes de\lCompra/Pagos

Admin -- (Comedor) : Presupuesto/Políticas ->
(Comedor) -right- Admin : <- Reportes \lFinancieros/Uso

'SGA -- (Comedor) : Verifica \lEstatus Estudiante ->
'(Comedor) -- SGA : <- Confirmación Acceso 


'Personal -[hidden] Proveedor
'Admin -[hidden] (Comedor)
'Personal -[hidden] (Comedor)
'Estudiante -[hidden] (Comedor)
'Proveedor -[hidden] (Comedor)
'SGA -[hidden] (Comedor)
@enduml