@startuml Requeriments
left to right direction
:Cliente:
:Administrador:
rectangle {
usecase 1Realizar_pedido
usecase 2Ver_menú
usecase 3Realizar_reporte
usecase 4Verificar_suministros
}
Cliente-->1Realizar_pedido
Cliente-->2Ver_menú
Administrador-->2Ver_menú
Administrador-->3Realizar_reporte
Administrador-->4Verificar_suministros
@enduml